version: "3.9"
services:
  oe-cache:
    image: "redis:alpine"
  oe-connector:
    image: 'docker-registry.groupclaes.be/groupclaes_oe-connector'
    ports:
      - '32000:80'
    volumes:
      - ./appsettings.json:/App/appsettings.json
